package server

import (
	"context"

	"connectrpc.com/connect"

	apiv1 "github.com/catouberos/transit-radar/gen/api/v1" // generated by protoc-gen-go
	"github.com/catouberos/transit-radar/internal/base"
)

func (s *RPCServer) CreateRoute(
	ctx context.Context,
	req *connect.Request[apiv1.CreateRouteRequest],
) (*connect.Response[apiv1.CreateRouteResponse], error) {
	result, err := s.App.RouteService.Create(ctx, base.CreateParams{
		Number:        req.Msg.Number,
		Name:          req.Msg.Name,
		EbmsID:        req.Msg.EbmsId,
		Active:        req.Msg.Active,
		OperationTime: req.Msg.OperationTime,
		Organization:  req.Msg.Organization,
		Ticketing:     req.Msg.Ticketing,
		RouteType:     req.Msg.RouteType,
	})
	if err != nil {
		return nil, err
	}
	route := buildRoute(result)

	res := connect.NewResponse(&apiv1.CreateRouteResponse{Route: route})
	return res, nil
}

func (s *RPCServer) UpdateRoute(
	ctx context.Context,
	req *connect.Request[apiv1.UpdateRouteRequest],
) (*connect.Response[apiv1.UpdateRouteResponse], error) {
	result, err := s.App.RouteService.Update(ctx, base.UpdateParams{
		Number:        req.Msg.Number,
		Name:          req.Msg.Name,
		EbmsID:        req.Msg.EbmsId,
		Active:        req.Msg.Active,
		OperationTime: req.Msg.OperationTime,
		Organization:  req.Msg.Organization,
		Ticketing:     req.Msg.Ticketing,
		RouteType:     req.Msg.RouteType,
	})
	if err != nil {
		return nil, err
	}
	route := buildRoute(result)

	res := connect.NewResponse(&apiv1.UpdateRouteResponse{Route: route})
	return res, nil
}

func (s *RPCServer) ListRoute(
	ctx context.Context,
	req *connect.Request[apiv1.ListRouteRequest],
) (*connect.Response[apiv1.ListRouteResponse], error) {
	results, err := s.App.RouteService.List(ctx, base.ListParams{})
	if err != nil {
		return nil, err
	}

	routes := []*apiv1.Route{}

	for _, result := range results {
		routes = append(routes, toResponseRoute(result))
	}

	res := connect.NewResponse(&apiv1.ListRouteResponse{Routes: routes})
	return res, nil
}

func (s *RPCServer) GetRoute(
	ctx context.Context,
	req *connect.Request[apiv1.GetRouteRequest],
) (*connect.Response[apiv1.GetRouteResponse], error) {
	result, err := s.App.GetRoute(ctx, req.Msg.Id)
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.GetRouteResponse{Route: toResponseRoute(result)})
	return res, nil
}

func buildRoute(in base.Route) *apiv1.Route {
	return &apiv1.Route{
		Id:            in.ID,
		Number:        in.Number,
		Name:          in.Name,
		Active:        in.Active,
		OperationTime: in.OperationTime,
		Organization:  in.Organization,
		Ticketing:     in.Ticketing,
		RouteType:     in.RouteType,
		EbmsId:        in.EbmsID,
	}
}
