package server

import (
	"context"
	"log"

	"connectrpc.com/connect"

	apiv1 "github.com/catouberos/transit-radar/gen/api/v1" // generated by protoc-gen-go
)

func (s *RPCServer) ListRoutes(
	ctx context.Context,
	req *connect.Request[apiv1.ListRoutesRequest],
) (*connect.Response[apiv1.ListRoutesResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&apiv1.ListRoutesResponse{})
	return res, nil
}
