package server

import (
	"net/http"

	connectcors "connectrpc.com/cors"
	"github.com/rs/cors"

	"github.com/catouberos/transit-radar/gen/api/v1/apiv1connect" // generated by protoc-gen-connect-go
	"github.com/catouberos/transit-radar/internal/app"
)

type RPCServer struct {
	App *app.App

	ListenAddr string
}

func NewRPCServer(app *app.App, listenAddr string) *RPCServer {
	server := &RPCServer{App: app, ListenAddr: listenAddr}

	return server
}

func (s *RPCServer) Serve() error {
	mux := http.NewServeMux()

	path, handler := apiv1connect.NewGeolocationServiceHandler(s)
	mux.Handle(path, withCORS(handler))

	path, handler = apiv1connect.NewRouteServiceHandler(s)
	mux.Handle(path, withCORS(handler))

	path, handler = apiv1connect.NewVariantServiceHandler(s)
	mux.Handle(path, withCORS(handler))

	path, handler = apiv1connect.NewVariantStopServiceHandler(s)
	mux.Handle(path, withCORS(handler))

	return http.ListenAndServe(s.ListenAddr, mux)
}

// withCORS adds CORS support to a Connect HTTP handler.
func withCORS(h http.Handler) http.Handler {
	middleware := cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: connectcors.AllowedMethods(),
		AllowedHeaders: connectcors.AllowedHeaders(),
		ExposedHeaders: connectcors.ExposedHeaders(),
	})
	return middleware.Handler(h)
}
