package server

import (
	"net/http"

	"github.com/catouberos/transit-radar/gen/api/v1/transitradarv1connect" // generated by protoc-gen-connect-go
)

type RPCServer struct{}

func NewRPCServer() *http.ServeMux {
	server := &RPCServer{}
	mux := http.NewServeMux()

	path, handler := transitradarv1connect.NewGeolocationServiceHandler(server)
	mux.Handle(path, handler)

	path, handler = transitradarv1connect.NewRouteServiceHandler(server)
	mux.Handle(path, handler)

	return mux
}
