package server

import (
	"context"

	"connectrpc.com/connect"

	apiv1 "github.com/catouberos/transit-radar/gen/api/v1" // generated by protoc-gen-go
	"github.com/catouberos/transit-radar/internal/variant"
)

func (s *RPCServer) CreateVariant(
	ctx context.Context,
	req *connect.Request[apiv1.CreateVariantRequest],
) (*connect.Response[apiv1.CreateVariantResponse], error) {
	result, err := s.App.VariantService.Create(ctx, variant.CreateParams{
		Name:          req.Msg.Name,
		EbmsID:        req.Msg.EbmsId,
		IsOutbound:    req.Msg.IsOutbound,
		RouteID:       req.Msg.RouteId,
		Description:   req.Msg.Description,
		ShortName:     req.Msg.ShortName,
		Distance:      req.Msg.Distance,
		Duration:      req.Msg.Duration,
		StartStopName: req.Msg.StartStopName,
		EndStopName:   req.Msg.EndStopName,
	})
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.CreateVariantResponse{Variant: toResponseVariant(result)})
	return res, nil
}

func (s *RPCServer) UpdateVariant(
	ctx context.Context,
	req *connect.Request[apiv1.UpdateVariantRequest],
) (*connect.Response[apiv1.UpdateVariantResponse], error) {
	result, err := s.App.VariantService.Update(ctx, variant.UpdateParams{
		Name:          req.Msg.Name,
		EbmsID:        req.Msg.EbmsId,
		IsOutbound:    req.Msg.IsOutbound,
		RouteID:       req.Msg.RouteId,
		Description:   req.Msg.Description,
		ShortName:     req.Msg.ShortName,
		Distance:      req.Msg.Distance,
		Duration:      req.Msg.Duration,
		StartStopName: req.Msg.StartStopName,
		EndStopName:   req.Msg.EndStopName,
	})
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.UpdateVariantResponse{Variant: toResponseVariant(result)})
	return res, nil
}

func (s *RPCServer) ListVariant(
	ctx context.Context,
	req *connect.Request[apiv1.ListVariantRequest],
) (*connect.Response[apiv1.ListVariantResponse], error) {
	results, err := s.App.VariantService.List(ctx, variant.ListParams{})
	if err != nil {
		return nil, err
	}

	routes := make([]*apiv1.Variant, len(results))
	for i, result := range results {
		routes[i] = toResponseVariant(result)
	}

	res := connect.NewResponse(&apiv1.ListVariantResponse{Variants: routes})
	return res, nil
}

func (s *RPCServer) GetVariant(
	ctx context.Context,
	req *connect.Request[apiv1.GetVariantRequest],
) (*connect.Response[apiv1.GetVariantResponse], error) {
	variant, err := s.App.VariantService.Get(ctx, variant.GetParams{ID: &req.Msg.Id})
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.GetVariantResponse{Variant: toResponseVariant(variant)})
	return res, nil
}

func (s *RPCServer) GetVariantByEbmsID(
	ctx context.Context,
	req *connect.Request[apiv1.GetVariantByEbmsIDRequest],
) (*connect.Response[apiv1.GetVariantByEbmsIDResponse], error) {
	variant, err := s.App.VariantService.Get(ctx, variant.GetParams{EbmsID: &req.Msg.EbmsId})
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.GetVariantByEbmsIDResponse{Variant: toResponseVariant(variant)})
	return res, nil
}

func toResponseVariant(in variant.Variant) *apiv1.Variant {
	return &apiv1.Variant{
		Id:            in.ID,
		Name:          in.Name,
		EbmsId:        in.EbmsID,
		IsOutbound:    in.IsOutbound,
		RouteId:       in.RouteID,
		Description:   in.Description,
		ShortName:     in.ShortName,
		Distance:      in.Distance,
		Duration:      in.Duration,
		StartStopName: in.StartStopName,
		EndStopName:   in.EndStopName,
	}
}
