package server

import (
	"context"

	"connectrpc.com/connect"

	apiv1 "github.com/catouberos/transit-radar/gen/api/v1" // generated by protoc-gen-go
	"github.com/catouberos/transit-radar/internal/variantstop"
)

func (s *RPCServer) CreateVariantStop(
	ctx context.Context,
	req *connect.Request[apiv1.CreateVariantStopRequest],
) (*connect.Response[apiv1.CreateVariantStopResponse], error) {
	result, err := s.App.VariantStopService.Create(ctx, variantstop.CreateParams{
		VariantID:  req.Msg.VariantId,
		StopID:     req.Msg.StopId,
		OrderScore: req.Msg.OrderScore,
	})
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.CreateVariantStopResponse{VariantStop: toResponseVariantStop(result)})
	return res, nil
}

func (s *RPCServer) UpdateVariantStop(
	ctx context.Context,
	req *connect.Request[apiv1.UpdateVariantStopRequest],
) (*connect.Response[apiv1.UpdateVariantStopResponse], error) {
	result, err := s.App.VariantStopService.Update(ctx, variantstop.UpdateParams{
		VariantID:  req.Msg.VariantId,
		StopID:     req.Msg.StopId,
		OrderScore: req.Msg.OrderScore,
	})
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.UpdateVariantStopResponse{VariantStop: toResponseVariantStop(result)})
	return res, nil
}

func (s *RPCServer) ListVariantStop(
	ctx context.Context,
	req *connect.Request[apiv1.ListVariantStopRequest],
) (*connect.Response[apiv1.ListVariantStopResponse], error) {
	results, err := s.App.VariantStopService.List(ctx, variantstop.ListParams{
		VariantID: req.Msg.VariantId,
		StopID:    req.Msg.StopId,
	})
	if err != nil {
		return nil, err
	}

	variantsStops := make([]*apiv1.VariantStop, 0, len(results))
	for _, result := range results {
		variantsStops = append(variantsStops, toResponseVariantStop(result))
	}

	res := connect.NewResponse(&apiv1.ListVariantStopResponse{VariantsStops: variantsStops})
	return res, nil
}

func (s *RPCServer) DeleteVariantStop(
	ctx context.Context,
	req *connect.Request[apiv1.DeleteVariantStopRequest],
) (*connect.Response[apiv1.DeleteVariantStopResponse], error) {
	err := s.App.VariantStopService.Delete(ctx, variantstop.DeleteParams{
		VariantID:  req.Msg.VariantId,
		OrderScore: req.Msg.OrderScore,
	})
	if err != nil {
		return nil, err
	}

	res := connect.NewResponse(&apiv1.DeleteVariantStopResponse{})
	return res, nil
}

func toResponseVariantStop(in variantstop.VariantStop) *apiv1.VariantStop {
	return &apiv1.VariantStop{
		VariantId:  in.VariantID,
		StopId:     in.StopID,
		OrderScore: in.OrderScore,
	}
}
