// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Geolocation struct {
	Degree      float32
	Latitude    float32
	Longitude   float32
	Speed       float32
	VehicleID   int64
	VariationID int64
	Timestamp   pgtype.Timestamptz
}

type Route struct {
	ID     int64
	Number string
	Name   string
	EbmsID pgtype.Int8
	Active bool
}

type Variation struct {
	ID         int64
	Name       string
	EbmsID     pgtype.Int8
	IsOutbound bool
	RouteID    int64
}

type Vehicle struct {
	ID           int64
	LicensePlate string
}
