// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: route.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO
    routes (
        number,
        name,
        ebms_id,
        operation_time,
        organization,
        ticketing,
        route_type
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7) RETURNING id, number, name, ebms_id, active, operation_time, organization, ticketing, route_type
`

type CreateRouteParams struct {
	Number        string
	Name          string
	EbmsID        pgtype.Int8
	OperationTime pgtype.Text
	Organization  pgtype.Text
	Ticketing     pgtype.Text
	RouteType     pgtype.Text
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Number,
		arg.Name,
		arg.EbmsID,
		arg.OperationTime,
		arg.Organization,
		arg.Ticketing,
		arg.RouteType,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.EbmsID,
		&i.Active,
		&i.OperationTime,
		&i.Organization,
		&i.Ticketing,
		&i.RouteType,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT
    id, number, name, ebms_id, active, operation_time, organization, ticketing, route_type
FROM
    routes
WHERE
    id = coalesce($1, id)
    AND ebms_id = coalesce($2, ebms_id)
LIMIT
    1
`

type GetRouteParams struct {
	ID     pgtype.Int8
	EbmsID pgtype.Int8
}

func (q *Queries) GetRoute(ctx context.Context, arg GetRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, arg.ID, arg.EbmsID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.EbmsID,
		&i.Active,
		&i.OperationTime,
		&i.Organization,
		&i.Ticketing,
		&i.RouteType,
	)
	return i, err
}

const listRoute = `-- name: ListRoute :many
SELECT
    id, number, name, ebms_id, active, operation_time, organization, ticketing, route_type
FROM
    routes
ORDER BY
    id
`

func (q *Queries) ListRoute(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.EbmsID,
			&i.Active,
			&i.OperationTime,
			&i.Organization,
			&i.Ticketing,
			&i.RouteType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE
    routes
SET
    number = coalesce($1, number),
    name = coalesce($2, name),
    ebms_id = coalesce($3, ebms_id),
    operation_time = coalesce($4, operation_time),
    organization = coalesce($5, organization),
    ticketing = coalesce($6, ticketing),
    route_type = coalesce($7, route_type)
WHERE
    id = $8 RETURNING id, number, name, ebms_id, active, operation_time, organization, ticketing, route_type
`

type UpdateRouteParams struct {
	Number        pgtype.Text
	Name          pgtype.Text
	EbmsID        pgtype.Int8
	OperationTime pgtype.Text
	Organization  pgtype.Text
	Ticketing     pgtype.Text
	RouteType     pgtype.Text
	ID            int64
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.Number,
		arg.Name,
		arg.EbmsID,
		arg.OperationTime,
		arg.Organization,
		arg.Ticketing,
		arg.RouteType,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.EbmsID,
		&i.Active,
		&i.OperationTime,
		&i.Organization,
		&i.Ticketing,
		&i.RouteType,
	)
	return i, err
}
