// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: route.sql

package models

import (
	"context"
)

const createRoute = `-- name: CreateRoute :one
INSERT INTO
    routes (
        number,
        name,
        short_name,
        description,
        "type",
        color,
        agency_id,
        active,
        attributes
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, number, name, short_name, description, type, color, agency_id, active, attributes
`

type CreateRouteParams struct {
	Number      string
	Name        string
	ShortName   *string
	Description *string
	Type        RouteType
	Color       *string
	AgencyID    int64
	Active      bool
	Attributes  []byte
}

func (q *Queries) CreateRoute(ctx context.Context, arg CreateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, createRoute,
		arg.Number,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.Type,
		arg.Color,
		arg.AgencyID,
		arg.Active,
		arg.Attributes,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.Type,
		&i.Color,
		&i.AgencyID,
		&i.Active,
		&i.Attributes,
	)
	return i, err
}

const getRoute = `-- name: GetRoute :one
SELECT
    id, number, name, short_name, description, type, color, agency_id, active, attributes
FROM
    routes
WHERE
    id = coalesce($1, id)
LIMIT
    1
`

func (q *Queries) GetRoute(ctx context.Context, id *int64) (Route, error) {
	row := q.db.QueryRow(ctx, getRoute, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.Type,
		&i.Color,
		&i.AgencyID,
		&i.Active,
		&i.Attributes,
	)
	return i, err
}

const listRoute = `-- name: ListRoute :many
SELECT
    id, number, name, short_name, description, type, color, agency_id, active, attributes
FROM
    routes
ORDER BY
    id
`

func (q *Queries) ListRoute(ctx context.Context) ([]Route, error) {
	rows, err := q.db.Query(ctx, listRoute)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.ShortName,
			&i.Description,
			&i.Type,
			&i.Color,
			&i.AgencyID,
			&i.Active,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE
    routes
SET
    number = coalesce($1, number),
    name = coalesce($2, name),
    short_name = coalesce($3, short_name),
    description = coalesce($4, description),
    "type" = coalesce($5, "type"),
    color = coalesce($6, color),
    agency_id = coalesce($7, agency_id),
    active = coalesce($8, active),
    attributes = coalesce($9, attributes)
WHERE
    id = $10 RETURNING id, number, name, short_name, description, type, color, agency_id, active, attributes
`

type UpdateRouteParams struct {
	Number      *string
	Name        *string
	ShortName   *string
	Description *string
	Type        NullRouteType
	Color       *string
	AgencyID    *int64
	Active      *bool
	Attributes  []byte
	ID          int64
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.Number,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.Type,
		arg.Color,
		arg.AgencyID,
		arg.Active,
		arg.Attributes,
		arg.ID,
	)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.Type,
		&i.Color,
		&i.AgencyID,
		&i.Active,
		&i.Attributes,
	)
	return i, err
}
