// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stop_type.sql

package models

import (
	"context"
)

const createStopType = `-- name: CreateStopType :one
INSERT INTO
    stop_types(name)
VALUES
    ($1) RETURNING id, name
`

func (q *Queries) CreateStopType(ctx context.Context, name string) (StopType, error) {
	row := q.db.QueryRow(ctx, createStopType, name)
	var i StopType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getStopType = `-- name: GetStopType :one
SELECT
    id, name
FROM
    stop_types
WHERE
    id = coalesce($1, id)
    AND name = coalesce($2, name)
LIMIT
    1
`

type GetStopTypeParams struct {
	ID   *int64
	Name *string
}

func (q *Queries) GetStopType(ctx context.Context, arg GetStopTypeParams) (StopType, error) {
	row := q.db.QueryRow(ctx, getStopType, arg.ID, arg.Name)
	var i StopType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listStopType = `-- name: ListStopType :many
SELECT
    id, name
FROM
    stop_types
ORDER BY
    id
`

func (q *Queries) ListStopType(ctx context.Context) ([]StopType, error) {
	rows, err := q.db.Query(ctx, listStopType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StopType
	for rows.Next() {
		var i StopType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStopType = `-- name: UpdateStopType :one
UPDATE
    stop_types
SET
    name = coalesce($1, name)
WHERE
    id = $2 RETURNING id, name
`

type UpdateStopTypeParams struct {
	Name *string
	ID   int64
}

func (q *Queries) UpdateStopType(ctx context.Context, arg UpdateStopTypeParams) (StopType, error) {
	row := q.db.QueryRow(ctx, updateStopType, arg.Name, arg.ID)
	var i StopType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
