// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stop_type.sql

package models

import (
	"context"
)

const createStopType = `-- name: CreateStopType :one
INSERT INTO
    stop_types (name)
VALUES
    ($1) RETURNING id, name
`

func (q *Queries) CreateStopType(ctx context.Context, name string) (StopType, error) {
	row := q.db.QueryRow(ctx, createStopType, name)
	var i StopType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getStopTypeByName = `-- name: GetStopTypeByName :one
SELECT
    id, name
FROM
    stop_types
WHERE
    name = $1
LIMIT
    1
`

func (q *Queries) GetStopTypeByName(ctx context.Context, name string) (StopType, error) {
	row := q.db.QueryRow(ctx, getStopTypeByName, name)
	var i StopType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
