// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: stop.sql

package models

import (
	"context"

	"github.com/cridenour/go-postgis"
)

const createStop = `-- name: CreateStop :one
INSERT INTO
    stops (
        parent_id,
        code,
        name,
        "type",
        active,
        location,
        attributes
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6 :: EWKB,
        $7
    ) RETURNING id, parent_id, code, name, type, active, location, attributes
`

type CreateStopParams struct {
	ParentID   *int64
	Code       string
	Name       string
	Type       StopType
	Active     bool
	Location   postgis.Point
	Attributes []byte
}

func (q *Queries) CreateStop(ctx context.Context, arg CreateStopParams) (Stop, error) {
	row := q.db.QueryRow(ctx, createStop,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Active,
		arg.Location,
		arg.Attributes,
	)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Active,
		&i.Location,
		&i.Attributes,
	)
	return i, err
}

const getStop = `-- name: GetStop :one
SELECT
    id, parent_id, code, name, type, active, location, attributes
FROM
    stops
WHERE
    id = coalesce($1, id)
LIMIT
    1
`

func (q *Queries) GetStop(ctx context.Context, id *int64) (Stop, error) {
	row := q.db.QueryRow(ctx, getStop, id)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Active,
		&i.Location,
		&i.Attributes,
	)
	return i, err
}

const listStop = `-- name: ListStop :many
SELECT
    id, parent_id, code, name, type, active, location, attributes
FROM
    stops
ORDER BY
    id
`

func (q *Queries) ListStop(ctx context.Context) ([]Stop, error) {
	rows, err := q.db.Query(ctx, listStop)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stop
	for rows.Next() {
		var i Stop
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.Type,
			&i.Active,
			&i.Location,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStop = `-- name: UpdateStop :one
UPDATE
    stops
SET
    parent_id = coalesce($1, parent_id),
    code = coalesce($2, code),
    name = coalesce($3, name),
    "type" = coalesce($4, "type"),
    active = coalesce($5, active),
    location = coalesce($6, location),
    attributes = coalesce($7, attributes)
WHERE
    id = $8 RETURNING id, parent_id, code, name, type, active, location, attributes
`

type UpdateStopParams struct {
	ParentID   *int64
	Code       *string
	Name       *string
	Type       NullStopType
	Active     *bool
	Location   postgis.Point
	Attributes []byte
	ID         int64
}

func (q *Queries) UpdateStop(ctx context.Context, arg UpdateStopParams) (Stop, error) {
	row := q.db.QueryRow(ctx, updateStop,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.Type,
		arg.Active,
		arg.Location,
		arg.Attributes,
		arg.ID,
	)
	var i Stop
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.Type,
		&i.Active,
		&i.Location,
		&i.Attributes,
	)
	return i, err
}
