// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: variant_stop.sql

package models

import (
	"context"
)

const createVariantStop = `-- name: CreateVariantStop :one
INSERT INTO
    variants_stops(
        variant_id,
        stop_id,
        order_score
    )
VALUES
    ($1, $2, $3) RETURNING variant_id, stop_id, order_score
`

type CreateVariantStopParams struct {
	VariantID  int64
	StopID     int64
	OrderScore int32
}

func (q *Queries) CreateVariantStop(ctx context.Context, arg CreateVariantStopParams) (VariantsStop, error) {
	row := q.db.QueryRow(ctx, createVariantStop, arg.VariantID, arg.StopID, arg.OrderScore)
	var i VariantsStop
	err := row.Scan(&i.VariantID, &i.StopID, &i.OrderScore)
	return i, err
}

const deleteVariantStop = `-- name: DeleteVariantStop :exec
DELETE FROM
    variants_stops
WHERE
    variant_id = $1
    AND order_score = $2
`

type DeleteVariantStopParams struct {
	VariantID  int64
	OrderScore int32
}

func (q *Queries) DeleteVariantStop(ctx context.Context, arg DeleteVariantStopParams) error {
	_, err := q.db.Exec(ctx, deleteVariantStop, arg.VariantID, arg.OrderScore)
	return err
}

const listVariantStop = `-- name: ListVariantStop :many
SELECT
    variant_id, stop_id, order_score
FROM
    variants_stops
WHERE
    variant_id = coalesce($1, variant_id)
    AND stop_id = coalesce($2, stop_id)
ORDER BY
    order_score ASC
`

type ListVariantStopParams struct {
	VariantID *int64
	StopID    *int64
}

func (q *Queries) ListVariantStop(ctx context.Context, arg ListVariantStopParams) ([]VariantsStop, error) {
	rows, err := q.db.Query(ctx, listVariantStop, arg.VariantID, arg.StopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariantsStop
	for rows.Next() {
		var i VariantsStop
		if err := rows.Scan(&i.VariantID, &i.StopID, &i.OrderScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariantStop = `-- name: UpdateVariantStop :one
UPDATE
    variants_stops
SET
    stop_id = $3
WHERE
    variant_id = $1
    AND order_score = $2 RETURNING variant_id, stop_id, order_score
`

type UpdateVariantStopParams struct {
	VariantID  int64
	OrderScore int32
	StopID     int64
}

func (q *Queries) UpdateVariantStop(ctx context.Context, arg UpdateVariantStopParams) (VariantsStop, error) {
	row := q.db.QueryRow(ctx, updateVariantStop, arg.VariantID, arg.OrderScore, arg.StopID)
	var i VariantsStop
	err := row.Scan(&i.VariantID, &i.StopID, &i.OrderScore)
	return i, err
}
