// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: variant.sql

package models

import (
	"context"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO
    variants (
        route_id,
        name,
        short_name,
        description,
        distance,
        direction,
        duration,
        attributes
    )
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, route_id, name, short_name, description, distance, direction, duration, attributes
`

type CreateVariantParams struct {
	RouteID     int64
	Name        string
	ShortName   *string
	Description string
	Distance    float32
	Direction   int32
	Duration    *int32
	Attributes  []byte
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.RouteID,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.Distance,
		arg.Direction,
		arg.Duration,
		arg.Attributes,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.Distance,
		&i.Direction,
		&i.Duration,
		&i.Attributes,
	)
	return i, err
}

const getVariant = `-- name: GetVariant :one
SELECT
    id, route_id, name, short_name, description, distance, direction, duration, attributes
FROM
    variants
WHERE
    id = coalesce($1, id)
    AND route_id = coalesce($2, route_id)
LIMIT
    1
`

type GetVariantParams struct {
	ID      *int64
	RouteID *int64
}

func (q *Queries) GetVariant(ctx context.Context, arg GetVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariant, arg.ID, arg.RouteID)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.Distance,
		&i.Direction,
		&i.Duration,
		&i.Attributes,
	)
	return i, err
}

const listVariant = `-- name: ListVariant :many
SELECT
    id, route_id, name, short_name, description, distance, direction, duration, attributes
FROM
    variants
WHERE
    route_id = coalesce($1, route_id)
ORDER BY
    id
`

func (q *Queries) ListVariant(ctx context.Context, routeID *int64) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariant, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.Name,
			&i.ShortName,
			&i.Description,
			&i.Distance,
			&i.Direction,
			&i.Duration,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE
    variants
SET
    route_id = coalesce($1, route_id),
    name = coalesce($2, name),
    short_name = coalesce($3, short_name),
    description = coalesce($4, description),
    distance = coalesce($5, distance),
    direction = coalesce($6, direction),
    duration = coalesce($7, duration),
    attributes = coalesce($8, attributes)
WHERE
    id = $9 RETURNING id, route_id, name, short_name, description, distance, direction, duration, attributes
`

type UpdateVariantParams struct {
	RouteID     *int64
	Name        *string
	ShortName   *string
	Description *string
	Distance    *float32
	Direction   *int32
	Duration    *int32
	Attributes  []byte
	ID          int64
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.RouteID,
		arg.Name,
		arg.ShortName,
		arg.Description,
		arg.Distance,
		arg.Direction,
		arg.Duration,
		arg.Attributes,
		arg.ID,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.Name,
		&i.ShortName,
		&i.Description,
		&i.Distance,
		&i.Direction,
		&i.Duration,
		&i.Attributes,
	)
	return i, err
}
