// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vehicle_type.sql

package models

import (
	"context"
)

const createVehicleType = `-- name: CreateVehicleType :one
INSERT INTO
    vehicle_types(name)
VALUES
    ($1) RETURNING id, name
`

func (q *Queries) CreateVehicleType(ctx context.Context, name string) (VehicleType, error) {
	row := q.db.QueryRow(ctx, createVehicleType, name)
	var i VehicleType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getVehicleType = `-- name: GetVehicleType :one
SELECT
    id, name
FROM
    vehicle_types
WHERE
    id = coalesce($1, id)
    AND name = coalesce($2, name)
LIMIT
    1
`

type GetVehicleTypeParams struct {
	ID   *int64
	Name *string
}

func (q *Queries) GetVehicleType(ctx context.Context, arg GetVehicleTypeParams) (VehicleType, error) {
	row := q.db.QueryRow(ctx, getVehicleType, arg.ID, arg.Name)
	var i VehicleType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listVehicleType = `-- name: ListVehicleType :many
SELECT
    id, name
FROM
    vehicle_types
ORDER BY
    id
`

func (q *Queries) ListVehicleType(ctx context.Context) ([]VehicleType, error) {
	rows, err := q.db.Query(ctx, listVehicleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleType
	for rows.Next() {
		var i VehicleType
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicleType = `-- name: UpdateVehicleType :one
UPDATE
    vehicle_types
SET
    name = coalesce($1, name)
WHERE
    id = $2 RETURNING id, name
`

type UpdateVehicleTypeParams struct {
	Name *string
	ID   int64
}

func (q *Queries) UpdateVehicleType(ctx context.Context, arg UpdateVehicleTypeParams) (VehicleType, error) {
	row := q.db.QueryRow(ctx, updateVehicleType, arg.Name, arg.ID)
	var i VehicleType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
