// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vehicle.sql

package models

import (
	"context"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO
    vehicles(license_plate)
VALUES
    ($1) RETURNING id, license_plate, type
`

func (q *Queries) CreateVehicle(ctx context.Context, licensePlate string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle, licensePlate)
	var i Vehicle
	err := row.Scan(&i.ID, &i.LicensePlate, &i.Type)
	return i, err
}

const getVehicleByLicensePlate = `-- name: GetVehicleByLicensePlate :one
SELECT
    id, license_plate, type
FROM
    vehicles
WHERE
    license_plate = $1
LIMIT
    1
`

func (q *Queries) GetVehicleByLicensePlate(ctx context.Context, licensePlate string) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleByLicensePlate, licensePlate)
	var i Vehicle
	err := row.Scan(&i.ID, &i.LicensePlate, &i.Type)
	return i, err
}
