// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protos/geolocation.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehiclesByRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       float32                `protobuf:"fixed32,1,opt,name=routeId,proto3" json:"routeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclesByRouteRequest) Reset() {
	*x = VehiclesByRouteRequest{}
	mi := &file_protos_geolocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclesByRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclesByRouteRequest) ProtoMessage() {}

func (x *VehiclesByRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_geolocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclesByRouteRequest.ProtoReflect.Descriptor instead.
func (*VehiclesByRouteRequest) Descriptor() ([]byte, []int) {
	return file_protos_geolocation_proto_rawDescGZIP(), []int{0}
}

func (x *VehiclesByRouteRequest) GetRouteId() float32 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

type VehiclesByRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclesByRouteResponse) Reset() {
	*x = VehiclesByRouteResponse{}
	mi := &file_protos_geolocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclesByRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclesByRouteResponse) ProtoMessage() {}

func (x *VehiclesByRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_geolocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclesByRouteResponse.ProtoReflect.Descriptor instead.
func (*VehiclesByRouteResponse) Descriptor() ([]byte, []int) {
	return file_protos_geolocation_proto_rawDescGZIP(), []int{1}
}

func (x *VehiclesByRouteResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type VehiclesByStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StationId     float32                `protobuf:"fixed32,1,opt,name=stationId,proto3" json:"stationId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclesByStationRequest) Reset() {
	*x = VehiclesByStationRequest{}
	mi := &file_protos_geolocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclesByStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclesByStationRequest) ProtoMessage() {}

func (x *VehiclesByStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_geolocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclesByStationRequest.ProtoReflect.Descriptor instead.
func (*VehiclesByStationRequest) Descriptor() ([]byte, []int) {
	return file_protos_geolocation_proto_rawDescGZIP(), []int{2}
}

func (x *VehiclesByStationRequest) GetStationId() float32 {
	if x != nil {
		return x.StationId
	}
	return 0
}

type VehiclesByStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclesByStationResponse) Reset() {
	*x = VehiclesByStationResponse{}
	mi := &file_protos_geolocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclesByStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclesByStationResponse) ProtoMessage() {}

func (x *VehiclesByStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_geolocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclesByStationResponse.ProtoReflect.Descriptor instead.
func (*VehiclesByStationResponse) Descriptor() ([]byte, []int) {
	return file_protos_geolocation_proto_rawDescGZIP(), []int{3}
}

func (x *VehiclesByStationResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type Vehicle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_protos_geolocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_protos_geolocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_protos_geolocation_proto_rawDescGZIP(), []int{4}
}

var File_protos_geolocation_proto protoreflect.FileDescriptor

const file_protos_geolocation_proto_rawDesc = "" +
	"\n" +
	"\x18protos/geolocation.proto\x12\x06protos\"2\n" +
	"\x16VehiclesByRouteRequest\x12\x18\n" +
	"\arouteId\x18\x01 \x01(\x02R\arouteId\"F\n" +
	"\x17VehiclesByRouteResponse\x12+\n" +
	"\bvehicles\x18\x01 \x03(\v2\x0f.protos.VehicleR\bvehicles\"8\n" +
	"\x18VehiclesByStationRequest\x12\x1c\n" +
	"\tstationId\x18\x01 \x01(\x02R\tstationId\"H\n" +
	"\x19VehiclesByStationResponse\x12+\n" +
	"\bvehicles\x18\x01 \x03(\v2\x0f.protos.VehicleR\bvehicles\"\t\n" +
	"\aVehicle2\xc5\x01\n" +
	"\vGeolocation\x12W\n" +
	"\x12GetVehiclesByRoute\x12\x1e.protos.VehiclesByRouteRequest\x1a\x1f.protos.VehiclesByRouteResponse\"\x00\x12]\n" +
	"\x14GetVehiclesByStation\x12 .protos.VehiclesByStationRequest\x1a!.protos.VehiclesByStationResponse\"\x00B%Z#github.com/catouberos/geoloc/protosb\x06proto3"

var (
	file_protos_geolocation_proto_rawDescOnce sync.Once
	file_protos_geolocation_proto_rawDescData []byte
)

func file_protos_geolocation_proto_rawDescGZIP() []byte {
	file_protos_geolocation_proto_rawDescOnce.Do(func() {
		file_protos_geolocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_geolocation_proto_rawDesc), len(file_protos_geolocation_proto_rawDesc)))
	})
	return file_protos_geolocation_proto_rawDescData
}

var file_protos_geolocation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protos_geolocation_proto_goTypes = []any{
	(*VehiclesByRouteRequest)(nil),    // 0: protos.VehiclesByRouteRequest
	(*VehiclesByRouteResponse)(nil),   // 1: protos.VehiclesByRouteResponse
	(*VehiclesByStationRequest)(nil),  // 2: protos.VehiclesByStationRequest
	(*VehiclesByStationResponse)(nil), // 3: protos.VehiclesByStationResponse
	(*Vehicle)(nil),                   // 4: protos.Vehicle
}
var file_protos_geolocation_proto_depIdxs = []int32{
	4, // 0: protos.VehiclesByRouteResponse.vehicles:type_name -> protos.Vehicle
	4, // 1: protos.VehiclesByStationResponse.vehicles:type_name -> protos.Vehicle
	0, // 2: protos.Geolocation.GetVehiclesByRoute:input_type -> protos.VehiclesByRouteRequest
	2, // 3: protos.Geolocation.GetVehiclesByStation:input_type -> protos.VehiclesByStationRequest
	1, // 4: protos.Geolocation.GetVehiclesByRoute:output_type -> protos.VehiclesByRouteResponse
	3, // 5: protos.Geolocation.GetVehiclesByStation:output_type -> protos.VehiclesByStationResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_geolocation_proto_init() }
func file_protos_geolocation_proto_init() {
	if File_protos_geolocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_geolocation_proto_rawDesc), len(file_protos_geolocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_geolocation_proto_goTypes,
		DependencyIndexes: file_protos_geolocation_proto_depIdxs,
		MessageInfos:      file_protos_geolocation_proto_msgTypes,
	}.Build()
	File_protos_geolocation_proto = out.File
	file_protos_geolocation_proto_goTypes = nil
	file_protos_geolocation_proto_depIdxs = nil
}
