// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Geolocation struct {
	Degree    pgtype.Float4
	Latitude  pgtype.Float4
	Longitude pgtype.Float4
	Speed     pgtype.Float4
	VehicleID pgtype.Int4
	RouteID   pgtype.Int4
	Timestamp pgtype.Timestamptz
}
